/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CccButtonQaq {
    }
    interface CccButtonQwq {
    }
    interface CccTemplate {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyComponent2 {
        /**
          * The first name
         */
        "first2": string;
        /**
          * The last name
         */
        "last2": string;
        /**
          * The middle name
         */
        "middle2": string;
    }
    interface MyName {
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
export interface MyComponent2CustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponent2Element;
}
declare global {
    interface HTMLCccButtonQaqElement extends Components.CccButtonQaq, HTMLStencilElement {
    }
    var HTMLCccButtonQaqElement: {
        prototype: HTMLCccButtonQaqElement;
        new (): HTMLCccButtonQaqElement;
    };
    interface HTMLCccButtonQwqElement extends Components.CccButtonQwq, HTMLStencilElement {
    }
    var HTMLCccButtonQwqElement: {
        prototype: HTMLCccButtonQwqElement;
        new (): HTMLCccButtonQwqElement;
    };
    interface HTMLCccTemplateElement extends Components.CccTemplate, HTMLStencilElement {
    }
    var HTMLCccTemplateElement: {
        prototype: HTMLCccTemplateElement;
        new (): HTMLCccTemplateElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyComponent2Element extends Components.MyComponent2, HTMLStencilElement {
    }
    var HTMLMyComponent2Element: {
        prototype: HTMLMyComponent2Element;
        new (): HTMLMyComponent2Element;
    };
    interface HTMLMyNameElement extends Components.MyName, HTMLStencilElement {
    }
    var HTMLMyNameElement: {
        prototype: HTMLMyNameElement;
        new (): HTMLMyNameElement;
    };
    interface HTMLElementTagNameMap {
        "ccc-button-qaq": HTMLCccButtonQaqElement;
        "ccc-button-qwq": HTMLCccButtonQwqElement;
        "ccc-template": HTMLCccTemplateElement;
        "my-component": HTMLMyComponentElement;
        "my-component2": HTMLMyComponent2Element;
        "my-name": HTMLMyNameElement;
    }
}
declare namespace LocalJSX {
    interface CccButtonQaq {
    }
    interface CccButtonQwq {
    }
    interface CccTemplate {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * name changed!
         */
        "onNamed"?: (event: MyComponentCustomEvent<string>) => void;
    }
    interface MyComponent2 {
        /**
          * The first name
         */
        "first2"?: string;
        /**
          * The last name
         */
        "last2"?: string;
        /**
          * The middle name
         */
        "middle2"?: string;
        /**
          * name changed!
         */
        "onNamed2"?: (event: MyComponent2CustomEvent<string>) => void;
    }
    interface MyName {
    }
    interface IntrinsicElements {
        "ccc-button-qaq": CccButtonQaq;
        "ccc-button-qwq": CccButtonQwq;
        "ccc-template": CccTemplate;
        "my-component": MyComponent;
        "my-component2": MyComponent2;
        "my-name": MyName;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ccc-button-qaq": LocalJSX.CccButtonQaq & JSXBase.HTMLAttributes<HTMLCccButtonQaqElement>;
            "ccc-button-qwq": LocalJSX.CccButtonQwq & JSXBase.HTMLAttributes<HTMLCccButtonQwqElement>;
            "ccc-template": LocalJSX.CccTemplate & JSXBase.HTMLAttributes<HTMLCccTemplateElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-component2": LocalJSX.MyComponent2 & JSXBase.HTMLAttributes<HTMLMyComponent2Element>;
            "my-name": LocalJSX.MyName & JSXBase.HTMLAttributes<HTMLMyNameElement>;
        }
    }
}
