/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { $Direction } from "./components/lottie-web/ccc-lottie-web-toggle-button.const";
import { AnimationItem, RendererType } from "lottie-web";
export namespace Components {
    interface CccCollectButton {
        "checkLabel": string;
        "checked": boolean;
        "direction": $Direction;
        "disabled": boolean;
        "icononly": boolean;
        "unCheckLabel": string;
    }
    interface CccCommentIcon {
        "direction": $Direction;
        "label": string;
    }
    interface CccDislikeButton {
        "checked": boolean;
        "count": number;
        "direction": $Direction;
        "disabled": boolean;
        "icononly": boolean;
    }
    interface CccLikeButton {
        "checked": boolean;
        "count": number;
        "direction": $Direction;
        "disabled": boolean;
        "icononly": boolean;
    }
    interface CccLottieWeb {
        /**
          * 是否要将动画至于末尾帧？
         */
        "actived": boolean;
        "autoplay": boolean;
        "data": object | undefined;
        "defaultActivedColor": string;
        "direction": 1 | -1;
        "getDuration": (isFrame?: boolean | undefined) => Promise<number | undefined>;
        "getInstance": () => Promise<AnimationItem | undefined>;
        "getPrimaryColor": () => Promise<string>;
        "goToAndPlay": (value: number, isFrame?: boolean | undefined, name?: string | undefined) => Promise<void | undefined>;
        "goToAndStop": (value: number, isFrame?: boolean | undefined, name?: string | undefined) => Promise<void | undefined>;
        "loop": boolean;
        "name": string;
        "pause": (name?: string | undefined) => Promise<void | undefined>;
        "play": (name?: string | undefined) => Promise<void | undefined>;
        /**
          * 渲染类型
         */
        "renderer": RendererType;
        "src": string | undefined;
        "togglePause": (name?: string | undefined) => Promise<void | undefined>;
    }
    interface CccLottieWebToggleButton {
        "animationData": object | undefined;
        "checked": boolean;
        "direction": $Direction;
        "disabled": boolean;
        "icononly": boolean;
        "label": string;
        "labelColor": string;
        "name": string;
    }
    interface CccTemplate {
        /**
          * click count
         */
        "count": number;
        /**
          * inc methid
         */
        "inc": () => Promise<void>;
    }
    interface CccUserCommentCard {
        "lineClamp": number;
        "text": string;
        "time": string;
        "userAvator": string;
        "userFlag": string;
        "userName": string;
    }
}
export interface CccLottieWebCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCccLottieWebElement;
}
export interface CccLottieWebToggleButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCccLottieWebToggleButtonElement;
}
export interface CccTemplateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCccTemplateElement;
}
export interface CccUserCommentCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCccUserCommentCardElement;
}
declare global {
    interface HTMLCccCollectButtonElement extends Components.CccCollectButton, HTMLStencilElement {
    }
    var HTMLCccCollectButtonElement: {
        prototype: HTMLCccCollectButtonElement;
        new (): HTMLCccCollectButtonElement;
    };
    interface HTMLCccCommentIconElement extends Components.CccCommentIcon, HTMLStencilElement {
    }
    var HTMLCccCommentIconElement: {
        prototype: HTMLCccCommentIconElement;
        new (): HTMLCccCommentIconElement;
    };
    interface HTMLCccDislikeButtonElement extends Components.CccDislikeButton, HTMLStencilElement {
    }
    var HTMLCccDislikeButtonElement: {
        prototype: HTMLCccDislikeButtonElement;
        new (): HTMLCccDislikeButtonElement;
    };
    interface HTMLCccLikeButtonElement extends Components.CccLikeButton, HTMLStencilElement {
    }
    var HTMLCccLikeButtonElement: {
        prototype: HTMLCccLikeButtonElement;
        new (): HTMLCccLikeButtonElement;
    };
    interface HTMLCccLottieWebElement extends Components.CccLottieWeb, HTMLStencilElement {
    }
    var HTMLCccLottieWebElement: {
        prototype: HTMLCccLottieWebElement;
        new (): HTMLCccLottieWebElement;
    };
    interface HTMLCccLottieWebToggleButtonElement extends Components.CccLottieWebToggleButton, HTMLStencilElement {
    }
    var HTMLCccLottieWebToggleButtonElement: {
        prototype: HTMLCccLottieWebToggleButtonElement;
        new (): HTMLCccLottieWebToggleButtonElement;
    };
    interface HTMLCccTemplateElement extends Components.CccTemplate, HTMLStencilElement {
    }
    var HTMLCccTemplateElement: {
        prototype: HTMLCccTemplateElement;
        new (): HTMLCccTemplateElement;
    };
    interface HTMLCccUserCommentCardElement extends Components.CccUserCommentCard, HTMLStencilElement {
    }
    var HTMLCccUserCommentCardElement: {
        prototype: HTMLCccUserCommentCardElement;
        new (): HTMLCccUserCommentCardElement;
    };
    interface HTMLElementTagNameMap {
        "ccc-collect-button": HTMLCccCollectButtonElement;
        "ccc-comment-icon": HTMLCccCommentIconElement;
        "ccc-dislike-button": HTMLCccDislikeButtonElement;
        "ccc-like-button": HTMLCccLikeButtonElement;
        "ccc-lottie-web": HTMLCccLottieWebElement;
        "ccc-lottie-web-toggle-button": HTMLCccLottieWebToggleButtonElement;
        "ccc-template": HTMLCccTemplateElement;
        "ccc-user-comment-card": HTMLCccUserCommentCardElement;
    }
}
declare namespace LocalJSX {
    interface CccCollectButton {
        "checkLabel"?: string;
        "checked"?: boolean;
        "direction"?: $Direction;
        "disabled"?: boolean;
        "icononly"?: boolean;
        "unCheckLabel"?: string;
    }
    interface CccCommentIcon {
        "direction"?: $Direction;
        "label"?: string;
    }
    interface CccDislikeButton {
        "checked"?: boolean;
        "count"?: number;
        "direction"?: $Direction;
        "disabled"?: boolean;
        "icononly"?: boolean;
    }
    interface CccLikeButton {
        "checked"?: boolean;
        "count"?: number;
        "direction"?: $Direction;
        "disabled"?: boolean;
        "icononly"?: boolean;
    }
    interface CccLottieWeb {
        /**
          * 是否要将动画至于末尾帧？
         */
        "actived"?: boolean;
        "autoplay"?: boolean;
        "data"?: object | undefined;
        "defaultActivedColor"?: string;
        "direction"?: 1 | -1;
        "loop"?: boolean;
        "name"?: string;
        "onCountChanged"?: (event: CccLottieWebCustomEvent<number>) => void;
        "onDefaultActivedColorChange"?: (event: CccLottieWebCustomEvent<string>) => void;
        "onEndFrame"?: (event: CccLottieWebCustomEvent<void>) => void;
        "onStartFrame"?: (event: CccLottieWebCustomEvent<void>) => void;
        /**
          * 渲染类型
         */
        "renderer"?: RendererType;
        "src"?: string | undefined;
    }
    interface CccLottieWebToggleButton {
        "animationData"?: object | undefined;
        "checked"?: boolean;
        "direction"?: $Direction;
        "disabled"?: boolean;
        "icononly"?: boolean;
        "label"?: string;
        "labelColor"?: string;
        "name"?: string;
        "onCheckedChange"?: (event: CccLottieWebToggleButtonCustomEvent<boolean>) => void;
    }
    interface CccTemplate {
        /**
          * click count
         */
        "count"?: number;
        "onCountChanged"?: (event: CccTemplateCustomEvent<number>) => void;
    }
    interface CccUserCommentCard {
        "lineClamp"?: number;
        "onClickUser"?: (event: CccUserCommentCardCustomEvent<void>) => void;
        "text"?: string;
        "time"?: string;
        "userAvator"?: string;
        "userFlag"?: string;
        "userName"?: string;
    }
    interface IntrinsicElements {
        "ccc-collect-button": CccCollectButton;
        "ccc-comment-icon": CccCommentIcon;
        "ccc-dislike-button": CccDislikeButton;
        "ccc-like-button": CccLikeButton;
        "ccc-lottie-web": CccLottieWeb;
        "ccc-lottie-web-toggle-button": CccLottieWebToggleButton;
        "ccc-template": CccTemplate;
        "ccc-user-comment-card": CccUserCommentCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ccc-collect-button": LocalJSX.CccCollectButton & JSXBase.HTMLAttributes<HTMLCccCollectButtonElement>;
            "ccc-comment-icon": LocalJSX.CccCommentIcon & JSXBase.HTMLAttributes<HTMLCccCommentIconElement>;
            "ccc-dislike-button": LocalJSX.CccDislikeButton & JSXBase.HTMLAttributes<HTMLCccDislikeButtonElement>;
            "ccc-like-button": LocalJSX.CccLikeButton & JSXBase.HTMLAttributes<HTMLCccLikeButtonElement>;
            "ccc-lottie-web": LocalJSX.CccLottieWeb & JSXBase.HTMLAttributes<HTMLCccLottieWebElement>;
            "ccc-lottie-web-toggle-button": LocalJSX.CccLottieWebToggleButton & JSXBase.HTMLAttributes<HTMLCccLottieWebToggleButtonElement>;
            "ccc-template": LocalJSX.CccTemplate & JSXBase.HTMLAttributes<HTMLCccTemplateElement>;
            "ccc-user-comment-card": LocalJSX.CccUserCommentCard & JSXBase.HTMLAttributes<HTMLCccUserCommentCardElement>;
        }
    }
}
